Core Manager: SubPagesController Class Reference
SubPagesController Class Reference
Class designated for UI subpages.
Inherits MonoBehaviour.
Public Member Functions
void OpenPage (UIPage page)
Showing canvas group sent thought parameter and disabling all others.
void AddPage (UIPage page, out Action openPage)
Adding new UIPage to this subpages controller
void AddPage (UIPage page, out UnityAction openPage)
Adding new UIPage to this subpages controller
void DelayedOpenPage (UIPage page)
Enables page interaction after delay
void DelayedOpenPage (UIPage page, float delay)
Enables page interaction after delay
void HideAllTables ()
Hides all pages in this subpage controller
Detailed Description
Class designated for UI subpages.
Definition at line 28 of file SubPagesController.cs.
Member Function Documentation
AddPage() [1/2]
void AddPage (UIPage page, out Action openPage) inline
Adding new UIPage to this subpages controller
Parameters
page
openPage
Definition at line 63 of file SubPagesController.cs.
References SubPagesController.OpenPage().
Referenced by UIManager.InitializeElements().
AddPage() [2/2]
void AddPage (UIPage page, out UnityAction openPage) inline
Adding new UIPage to this subpages controller
Parameters
page
openPage
Definition at line 74 of file SubPagesController.cs.
References SubPagesController.OpenPage().
DelayedOpenPage() [1/2]
void DelayedOpenPage (UIPage page) inline
Enables page interaction after delay
Parameters
page
Definition at line 99 of file SubPagesController.cs.
DelayedOpenPage() [2/2]
void DelayedOpenPage (UIPage page, float delay) inline
Enables page interaction after delay
Parameters
page
delay
Definition at line 109 of file SubPagesController.cs.
References UIStateTools.ChangeGroupState(), and SubPagesController.HideAllTables().
HideAllTables()
void HideAllTables () inline
Hides all pages in this subpage controller
Definition at line 120 of file SubPagesController.cs.
References UIStateTools.ChangeGroupState().
Referenced by SubPagesController.DelayedOpenPage(), and SubPagesController.OpenPage().
OpenPage()
void OpenPage (UIPage page) inline
Showing canvas group sent thought parameter and disabling all others.
Parameters
page
Definition at line 50 of file SubPagesController.cs.
References UIStateTools.ChangeGroupState(), and SubPagesController.HideAllTables().
Referenced by SubPagesController.AddPage().
The documentation for this class was generated from the following file:
CoreManager/Assets/CoreManager/UISystem/UI/SubPagesController.cs