Core Manager: CorePlugin.UISystem.UI.SubPagesController.HideAllTables
AddPage
AddPage
DelayedOpenPage
DelayedOpenPage
HideAllTables
OpenPage
HideAllTables()
void HideAllTables () inline
Hides all pages in this subpage controller
Definition at line 120 of file SubPagesController.cs.
References UIStateTools.ChangeGroupState().
Referenced by SubPagesController.DelayedOpenPage(), and SubPagesController.OpenPage().